# Generated by Django 5.1.1 on 2024-09-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formmodel',
            old_name='Compition',
            new_name='competition',
        ),
    ]
