# Generated by Django 5.1.1 on 2024-09-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_donatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=26)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
