# Generated by Django 5.1.1 on 2024-09-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_userdetailmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailmodel',
            name='Name',
            field=models.EmailField(max_length=26),
        ),
    ]
